import type { Game, GameType } from './types';

export const GAME_NAMES_BY_TYPE: Record<Game, string> = {
    americanFootball: 'TK_GAMES_AMERICAN-FOOTBALL',
    athletics: 'TK_GAMES_ATHLETICS',
    australianRulesFootball: 'TK_GAMES_AUSTRALIAN-RULES-FOOTBALL',
    badminton: 'TK_GAMES_BADMINTON',
    bandy: 'TK_GAMES_BANDY',
    baseball: 'TK_GAMES_BASEBALL',
    basketball: 'TK_GAMES_BASKETBALL',
    beachFootball: 'TK_GAMES_BEACH-FOOTBALL',
    beachVolleyball: 'TK_GAMES_BEACH-VOLLEYBALL',
    biathlon: 'TK_GAMES_BIATHLON',
    bowls: 'TK_GAMES_BOWLS',
    boxing: 'TK_GAMES_BOXING',
    callOfDuty: 'TK_GAMES_CALL-OF-DUTY',
    chess: 'TK_GAMES_CHESS',
    counterStrike: 'TK_GAMES_COUNTER-STRIKE',
    cricket: 'TK_GAMES_CRICKET',
    curling: 'TK_GAMES_CURLING',
    cyberBasketball: 'TK_GAMES_CYBER-BASKETBALL',
    cyberCricket: 'TK_GAMES_CYBER-CRICKET',
    cyberFootball: 'TK_GAMES_CYBER-FOOTBALL',
    cyberHockey: 'TK_GAMES_CYBER-HOCKEY',
    cyberKabaddi: 'TK_GAMES_CYBER-KABADDI',
    cyberSport: 'TK_GAMES_CYBERSPORT',
    cyberTableTennis: 'TK_GAMES_CYBER-TABLE-TENNIS',
    cyberTennis: 'TK_GAMES_CYBER-TENNIS',
    cyberVolleyball: 'TK_GAMES_CYBER-VOLLEYBALL',
    darts: 'TK_GAMES_DARTS',
    dota2: 'TK_GAMES_DOTA-2',
    fieldHockey: 'TK_GAMES_FIELD-HOCKEY',
    floorball: 'TK_GAMES_FLOORBALL',
    football: 'TK_GAMES_FOOTBALL',
    futsal: 'TK_GAMES_FUTSAL',
    golf: 'TK_GAMES_GOLF',
    handball: 'TK_GAMES_HANDBALL',
    hearthstone: 'TK_GAMES_HEARTHSTONE',
    iceHockey: 'TK_GAMES_HOCKEY',
    kabaddi: 'TK_GAMES_KABADDI',
    kingOfGlory: 'TK_GAMES_KING-OF-GLORY',
    leagueOfLegends: 'TK_GAMES_LEAGUE-OF-LEGENDS',
    lottery: 'TK_GAMES_LOTTERY',
    mma: 'TK_GAMES_MMA',
    motorSport: 'TK_GAMES_MOTOR-SPORT',
    olympics: 'TK_GAMES_OLYMPICS',
    politics: 'TK_GAMES_POLITICS',
    pubg: 'TK_GAMES_PUBG',
    rainbowSix: 'TK_GAMES_RAINBOW-SIX',
    rugby: 'TK_GAMES_RUGBY',
    snooker: 'TK_GAMES_SNOOKER',
    squash: 'TK_GAMES_SQUASH',
    starcraft: 'TK_GAMES_STARCRAFT',
    tableTennis: 'TK_GAMES_TABLE-TENNIS',
    tennis: 'TK_GAMES_TENNIS',
    ufc: 'TK_GAMES_UFC',
    unknown: 'TK_GAMES_UNKNOWN',
    valorant: 'TK_GAMES_VALORANT',
    virtualBasketball: 'TK_GAMES_VIRTUAL-BASKETBALL',
    virtualCricket: 'TK_GAMES_VIRTUAL-CRICKET',
    virtualFootball: 'TK_GAMES_VIRTUAL-FOOTBALL',
    virtualHockey: 'TK_GAMES_VIRTUAL-HOCKEY',
    virtualKabaddi: 'TK_GAMES_VIRTUAL-KABADDI',
    virtualTableTennis: 'TK_GAMES_VIRTUAL-TABLE-TENNIS',
    virtualTennis: 'TK_GAMES_VIRTUAL-TENNIS',
    virtualVolleyball: 'TK_GAMES_VIRTUAL-VOLLEYBALL',
    volleyball: 'TK_GAMES_VOLLEYBALL',
    waterPolo: 'TK_GAMES_WATER-POLO',
    worldOfTanks: 'TK_GAMES_WORLD-OF-TANKS',
};

export const GAMES: GameType[] = [
    { game: 'unknown', gameId: 0, gameName: GAME_NAMES_BY_TYPE.unknown, priority: 0 },
    {
        game: 'counterStrike',
        gameId: 4,
        gameName: GAME_NAMES_BY_TYPE.counterStrike,
        priority: 6,
        shortName: 'CS2',
    },
    {
        game: 'worldOfTanks',
        gameId: 1,
        gameName: GAME_NAMES_BY_TYPE.worldOfTanks,
        priority: 1,
        shortName: 'WoT',
    },
    {
        game: 'dota2',
        gameId: 2,
        gameName: GAME_NAMES_BY_TYPE.dota2,
        priority: 2,
        shortName: 'Dota2',
    },
    {
        game: 'leagueOfLegends',
        gameId: 3,
        gameName: GAME_NAMES_BY_TYPE.leagueOfLegends,
        priority: 3,
        shortName: 'LoL',
    },
    { game: 'kingOfGlory', gameId: 10, gameName: GAME_NAMES_BY_TYPE.kingOfGlory, priority: 4 },
    { game: 'starcraft', gameId: 11, gameName: GAME_NAMES_BY_TYPE.starcraft, priority: 5 },
    {
        game: 'valorant',
        gameId: 5,
        gameName: GAME_NAMES_BY_TYPE.valorant,
        priority: 7,
        shortName: 'Valorant',
    },
    { game: 'callOfDuty', gameId: 12, gameName: GAME_NAMES_BY_TYPE.callOfDuty, priority: 8 },
    { game: 'rainbowSix', gameId: 13, gameName: GAME_NAMES_BY_TYPE.rainbowSix, priority: 9 },
    { game: 'pubg', gameId: 6, gameName: GAME_NAMES_BY_TYPE.pubg, priority: 10 },
    { game: 'hearthstone', gameId: 7, gameName: GAME_NAMES_BY_TYPE.hearthstone, priority: 11 },
    { game: 'football', gameId: 20, gameName: GAME_NAMES_BY_TYPE.football, priority: 12 },
    { game: 'tennis', gameId: 21, gameName: GAME_NAMES_BY_TYPE.tennis, priority: 13 },
    { game: 'basketball', gameId: 22, gameName: GAME_NAMES_BY_TYPE.basketball, priority: 14 },
    { game: 'iceHockey', gameId: 23, gameName: GAME_NAMES_BY_TYPE.iceHockey, priority: 15 },
    { game: 'volleyball', gameId: 24, gameName: GAME_NAMES_BY_TYPE.volleyball, priority: 16 },
    { game: 'tableTennis', gameId: 25, gameName: GAME_NAMES_BY_TYPE.tableTennis, priority: 17 },
    { game: 'handball', gameId: 26, gameName: GAME_NAMES_BY_TYPE.handball, priority: 18 },
    {
        game: 'beachVolleyball',
        gameId: 27,
        gameName: GAME_NAMES_BY_TYPE.beachVolleyball,
        priority: 19,
    },
    { game: 'badminton', gameId: 28, gameName: GAME_NAMES_BY_TYPE.badminton, priority: 20 },
    { game: 'mma', gameId: 29, gameName: GAME_NAMES_BY_TYPE.mma, priority: 21 },
    {
        game: 'americanFootball',
        gameId: 30,
        gameName: GAME_NAMES_BY_TYPE.americanFootball,
        priority: 22,
    },
    { game: 'futsal', gameId: 31, gameName: GAME_NAMES_BY_TYPE.futsal, priority: 23 },
    { game: 'baseball', gameId: 32, gameName: GAME_NAMES_BY_TYPE.baseball, priority: 24 },
    { game: 'ufc', gameId: 33, gameName: GAME_NAMES_BY_TYPE.ufc, priority: 25 },
    { game: 'boxing', gameId: 34, gameName: GAME_NAMES_BY_TYPE.boxing, priority: 26 },
    {
        game: 'australianRulesFootball',
        gameId: 38,
        gameName: GAME_NAMES_BY_TYPE.australianRulesFootball,
        priority: 27,
    },
    { game: 'athletics', gameId: 39, gameName: GAME_NAMES_BY_TYPE.athletics, priority: 28 },
    { game: 'bandy', gameId: 40, gameName: GAME_NAMES_BY_TYPE.bandy, priority: 29 },
    { game: 'beachFootball', gameId: 41, gameName: GAME_NAMES_BY_TYPE.beachFootball, priority: 30 },
    { game: 'biathlon', gameId: 42, gameName: GAME_NAMES_BY_TYPE.biathlon, priority: 31 },
    { game: 'snooker', gameId: 43, gameName: GAME_NAMES_BY_TYPE.snooker, priority: 32 },
    { game: 'bowls', gameId: 44, gameName: GAME_NAMES_BY_TYPE.bowls, priority: 33 },
    { game: 'chess', gameId: 45, gameName: GAME_NAMES_BY_TYPE.chess, priority: 34 },
    { game: 'cricket', gameId: 46, gameName: GAME_NAMES_BY_TYPE.cricket, priority: 35 },
    { game: 'curling', gameId: 47, gameName: GAME_NAMES_BY_TYPE.curling, priority: 36 },
    { game: 'darts', gameId: 48, gameName: GAME_NAMES_BY_TYPE.darts, priority: 37 },
    { game: 'fieldHockey', gameId: 50, gameName: GAME_NAMES_BY_TYPE.fieldHockey, priority: 38 },
    { game: 'floorball', gameId: 51, gameName: GAME_NAMES_BY_TYPE.floorball, priority: 39 },
    { game: 'golf', gameId: 52, gameName: GAME_NAMES_BY_TYPE.golf, priority: 40 },
    { game: 'lottery', gameId: 53, gameName: GAME_NAMES_BY_TYPE.lottery, priority: 41 },
    { game: 'motorSport', gameId: 54, gameName: GAME_NAMES_BY_TYPE.motorSport, priority: 42 },
    { game: 'olympics', gameId: 55, gameName: GAME_NAMES_BY_TYPE.olympics, priority: 43 },
    { game: 'politics', gameId: 56, gameName: GAME_NAMES_BY_TYPE.politics, priority: 44 },
    { game: 'rugby', gameId: 57, gameName: GAME_NAMES_BY_TYPE.rugby, priority: 45 },
    { game: 'squash', gameId: 58, gameName: GAME_NAMES_BY_TYPE.squash, priority: 46 },
    { game: 'waterPolo', gameId: 59, gameName: GAME_NAMES_BY_TYPE.waterPolo, priority: 47 },
    { game: 'kabaddi', gameId: 61, gameName: GAME_NAMES_BY_TYPE.kabaddi, priority: 48 },
    { game: 'cyberSport', gameId: 62, gameName: GAME_NAMES_BY_TYPE.cyberSport, priority: 49 },
    {
        game: 'cyberFootball',
        gameId: 100,
        gameName: GAME_NAMES_BY_TYPE.cyberFootball,
        priority: 50,
    },
    { game: 'cyberHockey', gameId: 101, gameName: GAME_NAMES_BY_TYPE.cyberHockey, priority: 51 },
    { game: 'cyberTennis', gameId: 102, gameName: GAME_NAMES_BY_TYPE.cyberTennis, priority: 52 },
    {
        game: 'cyberTableTennis',
        gameId: 103,
        gameName: GAME_NAMES_BY_TYPE.cyberTableTennis,
        priority: 53,
    },
    {
        game: 'cyberBasketball',
        gameId: 104,
        gameName: GAME_NAMES_BY_TYPE.cyberBasketball,
        priority: 54,
    },
    {
        game: 'cyberVolleyball',
        gameId: 105,
        gameName: GAME_NAMES_BY_TYPE.cyberVolleyball,
        priority: 55,
    },
    { game: 'cyberCricket', gameId: 106, gameName: GAME_NAMES_BY_TYPE.cyberCricket, priority: 56 },
    { game: 'cyberKabaddi', gameId: 107, gameName: GAME_NAMES_BY_TYPE.cyberKabaddi, priority: 57 },
    {
        game: 'virtualFootball',
        gameId: 200,
        gameName: GAME_NAMES_BY_TYPE.virtualFootball,
        priority: 58,
    },
    {
        game: 'virtualHockey',
        gameId: 201,
        gameName: GAME_NAMES_BY_TYPE.virtualHockey,
        priority: 59,
    },
    {
        game: 'virtualTennis',
        gameId: 202,
        gameName: GAME_NAMES_BY_TYPE.virtualTennis,
        priority: 60,
    },
    {
        game: 'virtualTableTennis',
        gameId: 203,
        gameName: GAME_NAMES_BY_TYPE.virtualTableTennis,
        priority: 61,
    },
    {
        game: 'virtualBasketball',
        gameId: 204,
        gameName: GAME_NAMES_BY_TYPE.virtualBasketball,
        priority: 62,
    },
    {
        game: 'virtualVolleyball',
        gameId: 205,
        gameName: GAME_NAMES_BY_TYPE.virtualVolleyball,
        priority: 63,
    },
    {
        game: 'virtualCricket',
        gameId: 206,
        gameName: GAME_NAMES_BY_TYPE.virtualCricket,
        priority: 64,
    },
    {
        game: 'virtualKabaddi',
        gameId: 207,
        gameName: GAME_NAMES_BY_TYPE.virtualKabaddi,
        priority: 65,
    },
];

export const GAMES_INFO_BY_GAME = GAMES.reduce<Record<Game, GameType>>(
    (acc, item) => {
        acc[item.game] = item;

        return acc;
    },
    {} as Record<Game, GameType>,
);

export const GAMES_IDS_BY_GAME = GAMES.reduce<Record<Game, number>>(
    (acc, game) => {
        acc[game.game] = game.gameId;
        return acc;
    },
    {} as Record<Game, number>,
);

export const CHANNEL_GAMES_LIST: Game[] = [
    'counterStrike',
    'valorant',
    'dota2',
    'leagueOfLegends',
    'worldOfTanks',
];

export const DISPLAYED_CHANNELS_GAMES = GAMES.filter((item) =>
    CHANNEL_GAMES_LIST.includes(item.game as Game),
);

export const SPORT_GAMES_LIST: Game[] = ['football', 'basketball', 'iceHockey', 'tennis'];

export const DISPLAYED_SPORT_GAMES = GAMES.filter((item) =>
    SPORT_GAMES_LIST.includes(item.game as Game),
);
